-- AlterTable
ALTER TABLE "User" ADD COLUMN "baned" DATETIME;
ALTER TABLE "User" ADD COLUMN "isBanned" BOOLEAN;
ALTER TABLE "User" ADD COLUMN "isMuted" BOOLEAN;
ALTER TABLE "User" ADD COLUMN "muted" DATETIME;
